In [15]:
import numpy as np
# 1st task
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
#2nd taks
a3d = np.arange(0,9).reshape(3,3)
a3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#3rd task
ai = np.eye(3, dtype=int)
ai

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
#4th task
array = np.random.rand(3,3,3)
array


array([[[0.38191228, 0.2689338 , 0.91513463],
        [0.77689873, 0.99758352, 0.17256158],
        [0.64888472, 0.02905417, 0.1406941 ]],

       [[0.7844677 , 0.34435418, 0.58024607],
        [0.83061522, 0.56772104, 0.47945719],
        [0.80587285, 0.57423186, 0.30491942]],

       [[0.11234225, 0.13448661, 0.73361477],
        [0.26684086, 0.21421889, 0.5491015 ],
        [0.1926192 , 0.17772354, 0.28449179]]])

In [5]:
#5th task
ar1 = np.random.rand(10,10)
print(f"Max value:{np.max(ar1)}")
print(f"Min value:{np.min(ar1)}")


Max value:0.9752714469689009
Min value:0.0007335698432414661


In [6]:
#6th task
rv  = np.random.rand(30)
rvm = np.mean(rv)
rvm


np.float64(0.5494116678605673)

In [7]:
#7th task
m = np.random.rand(5,5)
m_normalized = (m - np.min(m))/(np.max(m) - np.min(m))
m_normalized

array([[0.2942057 , 0.02893207, 0.76058251, 0.78471777, 1.        ],
       [0.85415206, 0.40969657, 0.7925769 , 0.40978934, 0.70987418],
       [0.        , 0.1563147 , 0.37835262, 0.89499246, 0.97614722],
       [0.77766419, 0.83976822, 0.15529475, 0.53150744, 0.90708082],
       [0.76350811, 0.83299891, 0.86494244, 0.11068809, 0.22380283]])

In [8]:
#8th task
m1 = np.random.rand(5,3)
m2 = np.random.rand(3,2)
m3 = np.dot(m1, m2)
m3

array([[0.87718389, 0.79075099],
       [0.94875579, 1.19988831],
       [1.10654705, 0.71899681],
       [1.1580653 , 0.70960211],
       [0.78391442, 0.44671755]])

In [9]:
#9th task
b1 = np.random.rand(3,3)
b2 = np.random.rand(3,3)
dot = np.dot(b1, b2)
dot

array([[0.64104802, 0.44239267, 0.82715333],
       [0.40780099, 0.63753621, 0.52048835],
       [0.74270912, 0.61858563, 0.83960404]])

In [10]:
#10th task
tr = np.array([
       [0.10227094, 0.79063247, 0.97410599, 0.05466464],
       [0.20334829, 0.85488758, 0.20217198, 0.864468  ],
       [0.65813602, 0.50314702, 0.9512826 , 0.92782477],
       [0.96916518, 0.43311028, 0.25127859, 0.62197306]
       ])
print(tr.T, "\n")
print(np.transpose(tr))


[[0.10227094 0.20334829 0.65813602 0.96916518]
 [0.79063247 0.85488758 0.50314702 0.43311028]
 [0.97410599 0.20217198 0.9512826  0.25127859]
 [0.05466464 0.864468   0.92782477 0.62197306]] 

[[0.10227094 0.20334829 0.65813602 0.96916518]
 [0.79063247 0.85488758 0.50314702 0.43311028]
 [0.97410599 0.20217198 0.9512826  0.25127859]
 [0.05466464 0.864468   0.92782477 0.62197306]]


In [11]:
#11th task
matrix = np.array([
       [0.69714946, 0.40572431, 0.74433065],
       [0.67299475, 0.39653773, 0.81251367],
       [0.69933068, 0.62529149, 0.38590647]
       ])
print(f"its determinanat:{np.linalg.det(matrix)}")

its determinanat:-0.015526329003591233


In [28]:
#12th task
num = np.array([
[64, 78, 16, 51],
[66, 32, 74, 67],
[ 3, 11, 91, 94]])
num2 = np.array([
[12, 9, 21],
[22, 31, 7],
[26,77,41],
[6, 23, 95]])
mat_product = np.dot(num, num2)
mat_product

array([[ 3206,  5399,  7391],
       [ 3822,  8825, 11009],
       [ 3208,  9537, 12801]])

In [31]:
#13th task
mat1 = np.random.randint(1,20, size=(3,3))
vec = np.random.randint(1,20, size=(3,1))
cal = np.dot(mat1, vec)
cal


array([[158],
       [105],
       [295]], dtype=int32)

In [33]:
#14th task
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)
x = np.linalg.solve(A, b)
x

array([[ 1.55978845],
       [ 4.86360553],
       [-7.11745636]])

In [36]:
#15th task
giv = np.array([
       [3, 2, 3, 2, 7],
       [6, 7, 1, 9, 8],
       [9, 7, 9, 4, 7],
       [1, 3, 8, 5, 5],
       [9, 5, 9, 4, 4]])
column_sum = np.sum(giv, axis=0)
row_sum = np.sum(giv, axis=1)
print(f"row-wise sum:{row_sum}, column-wise sum:{column_sum}")

row-wise sum:[17 31 36 22 31], column-wise sum:[28 24 30 24 31]
